### ISSUE TITLE
Ordered Chunked Messages

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/chunked-dc-js#5]
Are they really necessary? When order of messages is guaranteed, chunking bytes is really straightforward. I doubt that I'd use a library if a simple loop with an offset is enough to divide a message into chunks.

On the other hand, if we do implement ordered chunked messages, with a different header than unordered messages, we complicate the protocol and the implementations. And all this just to save 9 bytes per chunk.

I'd rather keep things as simple as possible, and would try to avoid complexity sa far as possible.

What are your thoughts, @lgrahl?

**Comment by lgrahl** [comment]
We need ordered chunked messages to be able to recompose unordered (reliable or unreliable) messages. The reason: Although an unordered WebRTC Data Channel would not guarantee that messages are in order (and potentially not that they arrive at all), it **does guarantee** that datagrams are complete and byte-equal to the sent message. So, if we split a message into chunks, we still need to guarantee that chunks are recomposed to a message **in order** to ensure the messages' integrity.

Thus, we need a different behaviour anyway to recompose the message for unordered (and reliable or unreliable) channels, right? So, having a different header in that case doesn't seem to be a big issue (at least in JS that is) for me. Then again, you are correct that 9 bytes of 16K are nothing. We need to carefully weigh this up. But I think in the end it should come down to which one is easier to implement.

Let me know what you think @dbrgn.

**Comment by dbrgn** [comment]
I can't quite follow the first paragraph.

If we have an ordered dc, I can do something like this (pseudocode):

```
data = [1,2,3,4,5];
packets = simple_chunking_function(data, 2);
for (i in packets.length) {
    dc.send({
        done: i == packets.length - 1,
        packet: packet[i]
    );
}
```

And on the other side, collect them and concatenate them. No need for a message registry or anything like that. So in code that just handles ordered channels, I probably wouldn't use this library.

If on the other hand the user still wants to use our library (e.g. because he/she already uses it for unordered data channels), then the 9 byte overhead surely won't be a problem.

Regarding the case of unreliable channels, I don't think that makes sense at all. If you explicitly choose an unreliable channel, you're dealing with high-performance code and small packets (e.g. events). I can't come up with a use case where you'd want chunking on an unreliable channel.

**Comment by lgrahl** [comment]
Okay, let me explain it with a _worst case_ example. I'm sending the messages `hello` and `world` for all four combinations of ordered, unordered, reliable and unreliable where `hel` is the first chunk and `lo` the second chunk. The same applies to `world` where `wo` is the first chunk and `rld` the second chunk.

### Ordered, Reliable

`hel lo wo rld` - we only need to use the _end-of-message_ flag here, no need for the two additional 32 bit integers.

### Ordered, Unreliable

`lo wo rld` - _eom_ alone doesn't do the trick as we don't know how many chunks there were in the first place. Otherwise we'd accept `lo` as a complete message which would violate message integrity.

### Unordered, Reliable

`lo wo hel rld` - we need to reconstruct the order, so we need both message id, chunk id and _eom_ flag.

### Unordered, Unreliable

`lo hel rld` - same as above but we might see additional chunks being dropped, so reconstructing a message might not be possible.

What I was on about: Chunking on unreliable channels is a thing. Probably not that often but it doesn't hurt either as we need to implement the behaviour anyway if we want to support more modes than just ordered and reliable.

**Comment by dbrgn** [comment]
I see. The remaining question is whether the added complexity is worth it to save a few bytes per chunk.

A problem I see that could be happening is if the chunker is initialized as unordered on one side and as ordered on the other side. Then things would either break, or we'd have to introduce flags for the mode. If there's a flag regarding the mode, then in theory the unchunker should be able to assemble both ordered and unordered packets. I think that increases the complexity of the code by more than 100%.

Therefore I'd still go with a simple straightforward implementation that always sends the message id and chunk id along with the chunks. Then the chunker and unchunker only have one mode of operation, implementation is simple. If the few bytes are a problem for a performance critical implementation, then that implementation should use a custom, tailored solution anyways.

Complexity is the enemy of security, and we need to be careful not to overcomplicate things in the name of unmeasured performance :)

**Comment by lgrahl** [comment]
You're right about that. Then we should just write an implementation that can handle both unordered and unreliable channels at the same time and applies this behaviour to all modes.

**Comment by dbrgn** [comment]
Agree :) I think the Java implementation already got that covered with support for [unordered](https://github.com/saltyrtc/chunked-dc-java/blob/master/src/test/java/org/saltyrtc/chunkedDc/tests/UnchunkerTest.java#L55-L67) and [unreliable](https://github.com/saltyrtc/chunked-dc-java/blob/master/src/test/java/org/saltyrtc/chunkedDc/tests/UnchunkerTest.java#L83-L95) messages.
